repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: &flake8_version 5.0.4
    hooks:
      - &flake8_hook
        id: flake8
        additional_dependencies:
          - flake8-annotations~=2.7
          - flake8-bugbear==22.10.27
          - flake8-docstrings~=1.4
          - flake8-string-format~=0.3.0
          - flake8-todo~=0.7
          - pep8-naming~=0.12.1
          - pydocstyle~=6.1,!=6.1.0
  - repo: https://github.com/PyCQA/flake8
    rev: *flake8_version
    hooks:
      - <<: *flake8_hook
        alias: flake8-annotate
        name: flake8 (with annotations)
        stages: [manual]
        args: [
          --format,
          "::error file=%(path)s,line=%(row)d,col=%(col)d::[flake8] %(code)s: %(text)s",
        ]
