repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: flake8
        additional_dependencies: [
          pydocstyle ~= 4.0,
          "flake8-docstrings >= 1.3.1, == 1.*",
          flake8-bugbear ~= 19.3,
          flake8-import-order ~= 0.18.1,
          flake8-tidy-imports ~= 2.0,
          flake8-todo ~= 0.7,
          flake8-string-format ~= 0.2.3,
          flake8-quotes ~= 2.1
        ]
