apiVersion: apps/v1
kind: Deployment
metadata:
  name: snekbox
  namespace: snekbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snekbox
  template:
    metadata:
      labels:
        app: snekbox
    spec:
      initContainers:
        - name: deps-install
          image: ghcr.io/python-discord/snekbox:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: snekbox-user-base-volume
              mountPath: /snekbox/user_base
          command:
            - /bin/bash
            - scripts/install_eval_deps.sh
      containers:
        - name: snekbox
          image: ghcr.io/python-discord/snekbox:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8060
          securityContext:
            privileged: true
          volumeMounts:
            - name: snekbox-user-base-volume
              mountPath: /snekbox/user_base
      volumes:
        - name: snekbox-user-base-volume
          hostPath:
            path: /snekbox_dep_cache
            type: DirectoryOrCreate
