apiVersion: apps/v1
kind: Deployment
metadata:
  name: snekbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snekbox
  template:
    metadata:
      labels:
        app: snekbox
    spec:
      containers:
        - name: snekbox
          image: ghcr.io/python-discord/snekbox:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8060
          securityContext:
            privileged: true
          volumeMounts:
            - name: snekbox-user-base-volume
              mountPath: /snekbox/user_base
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - >-
                    PYTHONUSERBASE=/snekbox/user_base
                    pip install --user
                    anyio[trio]~=3.6
                    arrow~=1.2
                    attrs~=22.1
                    beautifulsoup4~=4.11
                    fishhook~=0.1
                    forbiddenfruit~=0.1
                    fuzzywuzzy~=0.18
                    lark~=1.1
                    more-itertools~=9.0
                    networkx~=2.8
                    numpy~=1.23
                    pandas~=1.5
                    pendulum~=2.1
                    python-dateutil~=2.8
                    pyyaml~=6.0
                    sympy~=1.11
                    toml~=0.10
                    typing-extensions~=4.4
                    tzdata~=2022.6
                    yarl~=1.8
      volumes:
        - name: snekbox-user-base-volume
          hostPath:
            path: /snekbox_dep_cache
            type: DirectoryOrCreate
