apiVersion: apps/v1
kind: Deployment
metadata:
  name: snekbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snekbox
  template:
    metadata:
      labels:
        app: snekbox
    spec:
      initContainers:
        - name: deps-install
          image: ghcr.io/python-discord/snekbox:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: snekbox-user-base-volume
              mountPath: /snekbox/user_base
          env:
            - name: PYTHONUSERBASE
              value: /snekbox/user_base
          command:
            - "/bin/sh"
            - "-c"
            - >-
              find /lang/python -mindepth 1 -maxdepth 1 -type d -exec
              {}/bin/python -m pip install --user -U -r requirements/eval-deps.pip \;
      containers:
        - name: snekbox
          image: ghcr.io/python-discord/snekbox:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8060
          securityContext:
            privileged: true
          volumeMounts:
            - name: snekbox-user-base-volume
              mountPath: /snekbox/user_base
      volumes:
        - name: snekbox-user-base-volume
          hostPath:
            path: /snekbox_dep_cache
            type: DirectoryOrCreate
